version: '3.8'
services:

  web:
    build: .
    container_name: wallet_cont
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wallet
      - SPRING_DATASOURCE_USERNAME=wallet
      - SPRING_DATASOURCE_PASSWORD=wallet

  db:
    image: postgres:14-alpine
    container_name: db_cont
    ports:
      - "4321:5432"
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_USER=wallet
      - POSTGRES_PASSWORD=wallet
